events {
    worker_connections 1024;
}

http {
    upstream wordpress {
        server wordpress:9000;
    }

    server {
        listen 443 ssl;
        server_name ddel-bla.42.fr;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.3;

        # Redirigir HTTP a HTTPS (opcional pero recomendado)
        error_page 497 https://$host:$server_port$request_uri;

        location / {
            proxy_pass http://wordpress;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ~ \.php$ {
            fastcgi_pass wordpress;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}