worker_processes auto;

pid /var/run/nginx/nginx.pid;

events {
	worker_connections 1024;
}

http {
	server {
		listen 443 ssl;
		server_name ddel-bla.42.fr;
		root /var/www/wordpress;

		ssl_certificate /etc/nginx/ssl/nginx.crt;
		ssl_certificate_key /etc/nginx/ssl/nginx.key;
		ssl_protocols TLSv1.3;

		error_page 497 https://$host$request_uri;

		location / {
			index index.php index.html;
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}
