[www]
user = wp-user
group = wp-user
listen = 9000
listen.owner = wp-user
listen.group = wp-user
listen.mode = 0660
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
chdir = /

; Pasar variables de entorno para WordPress
env[WORDPRESS_DB_HOST] = $WORDPRESS_DB_HOST
env[WORDPRESS_DB_USER] = $WORDPRESS_DB_USER
env[WORDPRESS_DB_PASSWORD] = $WORDPRESS_DB_PASSWORD
env[WORDPRESS_DB_NAME] = $WORDPRESS_DB_NAME
